import pandas as pd
from importlib import resources
from rdkit import Chem
import networkx as nx
from networkx.classes.digraph import DiGraph
import pickle
from rxn_insight.synthesis.knowledge_graph import KnowledgeGraph


def load_chem21_data():

    """
    Loads and processes the CHEM21 solvent data.

    This function reads a CSV file containing CHEM21 solvent data, processes it into
    multiple dictionaries for efficient solvent lookup by SMILES, CAS numbers, and names.

    Returns:
        dict: A dictionary containing the following keys:
            - 'solvent_smiles' (dict): Maps canonical SMILES or CAS numbers to solvent names.
            - 'smiles_solvent' (dict): Maps solvent names to canonical SMILES.
            - 'solvent_ranking' (dict): Maps solvent names to their CHEM21 ranking
              ('Recommended', 'Problematic', 'Hazardous').
            - 'cas_solvent' (dict): Maps solvent names to their CAS numbers.
    """

    with resources.path(f"rxn_insight.data", "chem21.csv") as path:
        chem21 = pd.read_csv(path, index_col=0)

    solvent_smiles = dict()
    solvent_problem = dict()
    solvent_ranking = dict()
    smiles_solvent = dict()
    cas_solvent = dict()
    for i in chem21.index:
        solvent_smiles[Chem.CanonSmiles(chem21["Smiles"][i])] = chem21["Name"][i].split("[")[0].strip()
        solvent_smiles[chem21["CAS"][i]] = chem21["Name"][i].split("[")[0].strip()
        smiles_solvent[chem21["Name"][i].split("[")[0].strip()] = Chem.CanonSmiles(chem21["Smiles"][i])
        cas_solvent[chem21["Name"][i].split("[")[0].strip()] = chem21["CAS"][i]
        solvent_problem[Chem.CanonSmiles(chem21["Smiles"][i])] = chem21["Default ranking"][i]
        solvent_problem[chem21["CAS"][i]] = chem21["Default ranking"][i]
    for s in solvent_problem.keys():
        solvent_ranking[solvent_smiles[s]] = solvent_problem[s]

    return {'solvent_smiles': solvent_smiles,
            'smiles_solvent': smiles_solvent,
            'solvent_ranking': solvent_ranking,
            'cas_solvent': cas_solvent}


def score_solvent(chem21_data: dict, smiles: str):

    """
    Evaluates the CHEM21 ranking of a solvent or mixture of solvents based on SMILES.

    Args:
        chem21_data (dict): The CHEM21 data dictionary generated by `load_chem21_data`.
        smiles (str): The SMILES representation of the solvent or mixture of solvents.
                      For mixtures, SMILES should be dot-separated.

    Returns:
        dict: A dictionary containing the following keys:
            - 'solvent_name' (str): The name of the solvent or mixture.
            - 'solvent_smiles' (str): The canonical SMILES of the solvent or mixture.
            - 'solvent_score' (str): The CHEM21 ranking of the solvent or mixture. Values can be:
                - "Recommended"
                - "Problematic"
                - "Hazardous"
                - "unknown" (if not present in the CHEM21 dataset)
    """

    if smiles == "":
        solvent_name = "solvent-free"
        solvent_smiles = ""
        solvent_score = "Recommended"

    elif "." in smiles:
        solvents = list(set(smiles.split(".")))
        in_chem21 = True
        solvent_names = []
        solvent_key = []
        for solvent in solvents:
            try:
                canonical_solvent = Chem.CanonSmiles(solvent)
            except Exception as e:
                canonical_solvent = solvent

            if canonical_solvent not in chem21_data['solvent_smiles']:
                in_chem21 = False
                solvent_names.append(canonical_solvent)
                solvent_key.append(canonical_solvent)

            else:
                solvent_names.append(chem21_data['solvent_smiles'][canonical_solvent])
                solvent_key.append(canonical_solvent)

        solvent_names = sorted(solvent_names)

        if len(solvent_names) > 2:
            named_solvent = "Mixture of "
            for j in range(len(solvent_names) - 1):
                named_solvent += solvent_names[j]
                named_solvent += ", "
            named_solvent += f"and {solvent_names[-1]}"
        else:
            named_solvent = f"Mixture of {solvent_names[0]} and {solvent_names[-1]}"

        if not in_chem21:
            solvent_name = named_solvent
            solvent_smiles = ".".join(solvent_key)
            solvent_score = "unknown"

        else:
            traffic = {"Recommended": 0, "Problematic": 1, "Hazardous": 2}
            traffic_inv = {0: "Recommended", 1: "Problematic", 2: "Hazardous"}
            score_list = []

            for key in solvent_key:
                score_list.append(traffic[chem21_data['solvent_ranking'][chem21_data['solvent_smiles'][key]]])

            solvent_name = named_solvent
            solvent_smiles = ".".join(solvent_key)
            solvent_score = traffic_inv[max(score_list)]

    else:
        try:
            canonical_solvent = Chem.CanonSmiles(smiles)
        except Exception as e:
            canonical_solvent = smiles

        if canonical_solvent not in chem21_data['solvent_smiles']:
            solvent_name = canonical_solvent
            solvent_smiles = canonical_solvent
            solvent_score = 'unknown'
        else:
            solvent_name = chem21_data['solvent_smiles'][canonical_solvent]
            solvent_smiles = canonical_solvent
            solvent_score = chem21_data['solvent_ranking'][solvent_name]

    return {'solvent_name': solvent_name,
            'solvent_smiles': solvent_smiles,
            'solvent_score': solvent_score}


def load_gsk_ssg_data():
    """
    Loads and processes the GSK SSG (Sustainable Solvents Guide) data.

    This function reads a CSV file containing GSK SSG solvent data and creates
    multiple dictionaries for efficient solvent lookup by SMILES, CAS numbers, and names.

    Returns:
        dict: A dictionary containing the following keys:
            - 'solvent_smiles' (dict): Maps canonical SMILES or CAS numbers to solvent names.
            - 'smiles_solvent' (dict): Maps solvent names to canonical SMILES.
            - 'cas_solvent' (dict): Maps solvent names to their CAS numbers.
            - 'solvent_scores' (dict): Maps solvent names to their GSK SSG scores dictionary.
    """
    with resources.path(f"rxn_insight.data", "gsk_ssg.csv") as path:
        gsk_ssg = pd.read_csv(path, index_col=0)

    solvent_smiles = dict()
    smiles_solvent = dict()
    cas_solvent = dict()
    solvent_scores = dict()

    for i in gsk_ssg.index:
        canonical_smiles = Chem.CanonSmiles(gsk_ssg["smiles"][i])
        solvent_name = gsk_ssg["name"][i]
        cas_number = gsk_ssg["CAS"][i]

        # Map SMILES and CAS to solvent name
        solvent_smiles[canonical_smiles] = solvent_name
        solvent_smiles[cas_number] = solvent_name

        # Map solvent name to SMILES and CAS
        smiles_solvent[solvent_name] = canonical_smiles
        cas_solvent[solvent_name] = cas_number

        # Store all scores for each solvent
        solvent_scores[solvent_name] = {
            'incineration': int(round(gsk_ssg["Incineration"][i])),
            'recycling': int(round(gsk_ssg["Recycling"][i])),
            'bio_treatment': int(round(gsk_ssg["Bio-treatment"][i])),
            'voc_emissions': int(round(gsk_ssg["VOC emissions"][i])),
            'environment_water': int(round(gsk_ssg["Environment - water"][i])),
            'environment_air': int(round(gsk_ssg["Environment - air"][i])),
            'health': int(round(gsk_ssg["Health"][i])),
            'exposure': int(round(gsk_ssg["Exposure"][i])),
            'flammability': int(round(gsk_ssg["Flamability"][i])),
            'stability': int(round(gsk_ssg["Stability"][i])),
            'waste_score': int(round(gsk_ssg["waste_score"][i])),
            'environment_score': int(round(gsk_ssg["environment_score"][i])),
            'health_score': int(round(gsk_ssg["health_score"][i])),
            'safety_score': int(round(gsk_ssg["safety_score"][i])),
            'total_score': int(round(gsk_ssg["total_score"][i]))
        }

    return {
        'solvent_smiles': solvent_smiles,
        'smiles_solvent': smiles_solvent,
        'cas_solvent': cas_solvent,
        'solvent_scores': solvent_scores
    }


def score_solvent_gsk(gsk_data: dict, smiles: str):
    """
    Evaluates the GSK SSG scores of a solvent or mixture of solvents based on SMILES.

    For mixtures, the worst score (lowest value) is taken for each category, as lower
    scores indicate greater concern in the GSK SSG system (10 = best, 1 = worst).

    Args:
        gsk_data (dict): The GSK SSG data dictionary generated by `load_gsk_ssg_data`.
        smiles (str): The SMILES representation of the solvent or mixture of solvents.
                      For mixtures, SMILES should be dot-separated.

    Returns:
        dict: A dictionary containing the following keys:
            - 'solvent_name' (str): The name of the solvent or mixture.
            - 'solvent_smiles' (str): The canonical SMILES of the solvent or mixture.
            - 'scores' (dict): Dictionary of all GSK SSG scores, including:
                - Individual metrics (incineration, recycling, etc.)
                - Aggregate scores (waste_score, environment_score, etc.)
                - 'status' (str): "known" if in GSK SSG database, "unknown" otherwise
    """
    if smiles == "":
        # Solvent-free conditions get the best possible scores (10/10)
        return {
            'solvent_name': "solvent-free",
            'solvent_smiles': "",
            'scores': {
                'incineration': 10,
                'recycling': 10,
                'bio_treatment': 10,
                'voc_emissions': 10,
                'environment_water': 10,
                'environment_air': 10,
                'health': 10,
                'exposure': 10,
                'flammability': 10,
                'stability': 10,
                'waste_score': 10,
                'environment_score': 10,
                'health_score': 10,
                'safety_score': 10,
                'total_score': 10,
                'status': 'known'
            }
        }

    elif "." in smiles:
        # Handle solvent mixtures
        solvents = list(set(smiles.split(".")))
        in_gsk = True
        solvent_names = []
        solvent_keys = []
        all_scores = []

        for solvent in solvents:
            try:
                canonical_solvent = Chem.CanonSmiles(solvent)
            except Exception:
                canonical_solvent = solvent

            if canonical_solvent not in gsk_data['solvent_smiles']:
                in_gsk = False
                solvent_names.append(canonical_solvent)
                solvent_keys.append(canonical_solvent)
            else:
                solvent_name = gsk_data['solvent_smiles'][canonical_solvent]
                solvent_names.append(solvent_name)
                solvent_keys.append(canonical_solvent)
                all_scores.append(gsk_data['solvent_scores'][solvent_name])

        solvent_names = sorted(solvent_names)

        # Format mixture name
        if len(solvent_names) > 2:
            named_solvent = "Mixture of "
            for j in range(len(solvent_names) - 1):
                named_solvent += solvent_names[j]
                named_solvent += ", "
            named_solvent += f"and {solvent_names[-1]}"
        else:
            named_solvent = f"Mixture of {solvent_names[0]} and {solvent_names[-1]}"

        if not in_gsk or not all_scores:
            # Unknown mixture
            return {
                'solvent_name': named_solvent,
                'solvent_smiles': ".".join(solvent_keys),
                'scores': {
                    'status': 'unknown'
                }
            }
        else:
            # For mixtures, take the worst (lowest) score for each category
            worst_scores = {}
            score_keys = all_scores[0].keys()

            for key in score_keys:
                worst_scores[key] = min(score[key] for score in all_scores)

            worst_scores['status'] = 'known'

            return {
                'solvent_name': named_solvent,
                'solvent_smiles': ".".join(solvent_keys),
                'scores': worst_scores
            }

    else:
        # Single solvent
        try:
            canonical_solvent = Chem.CanonSmiles(smiles)
        except Exception:
            canonical_solvent = smiles

        if canonical_solvent not in gsk_data['solvent_smiles']:
            return {
                'solvent_name': canonical_solvent,
                'solvent_smiles': canonical_solvent,
                'scores': {
                    'status': 'unknown'
                }
            }
        else:
            solvent_name = gsk_data['solvent_smiles'][canonical_solvent]
            scores = gsk_data['solvent_scores'][solvent_name].copy()
            scores['status'] = 'known'

            return {
                'solvent_name': solvent_name,
                'solvent_smiles': canonical_solvent,
                'scores': scores
            }


def get_gsk_score_description():
    """
    Returns a description of the GSK SSG scoring system.

    Returns:
        dict: A dictionary explaining the meaning of each score category.
    """
    return {
        'score_ranges': {
            'description': 'All scores are on a 1-10 scale, where 10 is best and 1 is worst',
            'interpretation': {
                '9-10': 'Best - Low environmental/health/safety concern',
                '7-8': 'Good - Moderate concern',
                '5-6': 'Fair - Significant concern',
                '3-4': 'Poor - High concern',
                '1-2': 'Worst - Very high concern'
            }
        },
        'individual_metrics': {
            'incineration': 'Environmental impact when incinerated (10 = minimal impact)',
            'recycling': 'Ease of recycling (10 = easily recyclable)',
            'bio_treatment': 'Biodegradability (10 = readily biodegradable)',
            'voc_emissions': 'VOC emissions potential (10 = low emissions)',
            'environment_water': 'Impact on aquatic environment (10 = minimal impact)',
            'environment_air': 'Impact on air quality (10 = minimal impact)',
            'health': 'Human health hazards (10 = low hazard)',
            'exposure': 'Potential for human exposure (10 = low exposure potential)',
            'flammability': 'Fire hazard (10 = low flammability)',
            'stability': 'Chemical stability (10 = highly stable)'
        },
        'aggregate_scores': {
            'waste_score': 'Combined score for waste management',
            'environment_score': 'Combined environmental impact score',
            'health_score': 'Combined health and exposure score',
            'safety_score': 'Combined flammability and stability score',
            'total_score': 'Overall sustainability score'
        }
    }


def get_all_buyables():

    """
    Loads a price list of buyable compounds and their prices from a CSV file.

    Returns:
        dict: A dictionary mapping SMILES strings of compounds to their prices in Euros
              for 10 grams.
    """

    with resources.path(f"rxn_insight.data", "pricelist_10g.csv") as path:
        price_list = pd.read_csv(path, index_col=0)

    buyables = {}
    for i in price_list.index:
        buyables[price_list["SMILES"][i]] = price_list["Price_EUR_10g"][i]

    return buyables


def get_flow_ef():

    """
    Loads a dictionary containing flow enhancement factor data from a pickle file.

    Returns:
        dict: A dictionary with flow enhancement factor data.
    """

    with resources.path(f"rxn_insight.data", "flow_ef_dict.pkl") as path:
        with open(path, "rb") as f:
            flow_ef_dict = pickle.load(f)

    return flow_ef_dict


def load_graph(graph_name: str = "flow_graph"):

    """
    Loads a graph in GML format.

    Args:
        graph_name (str): The name of the graph file (without the ".gml" extension).
                          Defaults to "flow_graph".

    Returns:
        networkx.Graph: A NetworkX graph object loaded from the GML file.
    """

    with resources.path(f"rxn_insight.data", graph_name + ".gml") as path:
        graph = nx.read_gml(path)

    return graph


def load_pickled_flow_graph() -> DiGraph:

    """
    Loads the default flow graph from a pickle file.

    Returns:
        networkx.DiGraph: A directed NetworkX graph object loaded from the pickle file.
    """

    with resources.path(f"rxn_insight.data", "flow_graph.gpickle") as path:
        with open(path, 'rb') as f:
            graph = pickle.load(f)

    return graph


def load_pickled_graph(graph_name: str = "flow_graph") -> DiGraph:

    """
    Loads a pickled directed graph by name.

    Args:
        graph_name (str): The name of the pickled graph file (without the ".gpickle" extension).
                          Defaults to "flow_graph".

    Returns:
        networkx.DiGraph: A directed NetworkX graph object loaded from the pickle file.
    """

    with resources.path(f"rxn_insight.data", graph_name + ".gpickle") as path:
        with open(path, 'rb') as f:
            graph = pickle.load(f)

    return graph


def load_graph_from_file(graph_name: str) -> KnowledgeGraph:

    """
    Loads a pickled directed graph by name.

    Args:
        graph_name (str): The name of the pickled graph file (with the ".gpickle" extension).

    Returns:
        networkx.DiGraph: A directed NetworkX graph object loaded from the pickle file.
    """

    with open(graph_name, 'rb') as f:
        graph = pickle.load(f)

    return KnowledgeGraph(graph)


def load_pickled_uspto_graph() -> DiGraph:

    """
    Loads the USPTO graph from a pickle file.

    Returns:
        networkx.DiGraph: A directed NetworkX graph object loaded from the pickle file.
    """

    with resources.path(f"rxn_insight.data", "uspto_graph.gpickle") as path:
        with open(path, 'rb') as f:
            graph = pickle.load(f)

    return graph


def get_reaction_subcategories():
    categorized_reactions = {
        "Stille Reaction": [
            "Stille reaction_vinyl", "Stille reaction_aryl", "Stille reaction_allyl",
            "Stille reaction_other", "Stille reaction_vinyl OTf", "Stille reaction_allyl OTf",
            "Stille reaction_benzyl", "Stille", "Stille reaction_aryl OTf"
        ],
        "Suzuki Coupling": [
            "Suzuki coupling with sulfonic esters", "Suzuki coupling with boronic acids",
            "Suzuki coupling with boronic acids OTf", "Suzuki coupling with boronic esters OTf",
            "Suzuki coupling with boronic esters", "Suzuki"
        ],
        "Minisci Reaction": [
            "Minisci (ortho)", "Minisci (ortho-cyanide)", "Minisci (para)", "Minisci (para-cyanide)",
            "Minisci-like halide substitution"
        ],
        "Mitsunobu Reaction": [
            "Mitsunobu_imide", "Mitsunobu aryl ether", "Mitsunobu_sulfonamide",
            "Mitsunobu esterification", "Mitsunobu_tetrazole_3", "Mitsunobu_tetrazole_4",
            "Mitsunobu_tetrazole_1", "Mitsunobu_tetrazole_2"
        ],
        "Heck Reaction": [
            "Heck terminal vinyl", "Oxidative Heck reaction with vinyl ester",
            "Heck reaction with vinyl ester and amine","Oxidative Heck reaction", "Heck_non-terminal_vinyl"
        ],
        "Williamson Ether Synthesis": [
            "Williamson Ether Synthesis", "Williamson Ether Synthesis (intra to epoxy)"
        ],
        "Buchwald-Hartwig/Ullmann-Goldberg Coupling": [
            "Buchwald-Hartwig/Ullmann-Goldberg/N-arylation secondary amine",
            "Buchwald-Hartwig/Ullmann-Goldberg/N-arylation primary amine",
            "N-arylation (Buchwald-Hartwig/Ullmann-Goldberg)",
            "Ullmann-Goldberg Substitution thiol",
            "Ullmann-Goldberg Substitution amine",
            "Goldberg coupling aryl amine-aryl chloride",
            "Goldberg coupling"
        ],
        "Huisgen 1,3-Dipolar Cycloaddition": [
            "Huisgen alkyne-azide 1,3 dipolar cycloaddition", "Huisgen 1,3 dipolar cycloaddition",
            "Huisgen alkene-azide 1,3 dipolar cycloaddition"
        ],
        "Grignard Reaction": [
            "Grignard with CO2 to carboxylic acid", "Grignard_alcohol", "Grignard from aldehyde to alcohol",
            "Grignard from ketone to alcohol", "Grignard_carbonyl"
        ],
        "Wittig Reaction": [
            "Wittig reaction with triphenylphosphorane", "Wittig", "Wittig with Phosphonium"
        ],
        "Petasis Reaction": [
            "Petasis reaction with amines and boronic acids", "Petasis reaction with amines and boronic esters",
            "Petasis reaction with amines aldehydes and boronic acids"
        ],
        "Sonogashira Coupling": [
            "Sonogashira alkyne_alkenyl halide", "Sonogashira alkyne_aryl halide",
            "Sonogashira acetylene_acyl halide"
        ],
        "Methylation": [
            "Eschweiler-Clarke Primary Amine Methylation", "Eschweiler-Clarke Secondary Amine Methylation",
            "Methylation with MeI_primary", "Methylation with MeI_secondary", "Methylation with MeI_tertiary",
            "Methylation with MeI_aryl", "Methylation with MeI_SH", "Methylation",
            "Methylation of OH with DMS", "Methylation with DMS", "Methylation with DMC",
            "DMS COOH methylation", "DMS Amine methylation", "Reductive methylation of primary amine with formaldehyde",
            "Parnes methylation", "N-methylation", "S-methylation", "O-methylation", "C-methylation"
        ],
        "Schmidt Reaction": [
            "Schmidt reaction nitrile", "Schmidt ketone amide", "Schmidt aldehyde amide"
        ],
        "Catellani Reaction": [
            "Catellani reaction para", "Catellani reaction ortho"
        ],
        "Diels-Alder Reaction": [
            "Diels-Alder (ON bond)", "Diels-Alder"
        ],
        "Negishi Coupling": [
            "Negishi coupling", "Negishi"
        ],
        "Michael Addition": [
            "aza-Michael addition secondary", "aza-Michael addition primary", "aza-Michael addition aromatic",
            "Michael addition methyl", "Michael addition", "thia-Michael addition", "oxa-Michael addition"
        ],
        "Michael-induced Ring Closure": [
            "Michael-induced ring closure from hydrazone", "Michael-induced ring closure from diazoalkane"
        ],
        "Hydrogenation": [
            "Hydrogenation (double to single)", "Hydrogenation (triple to double)"
        ],
        "Cleavage Reactions": [
            "Cleavage of sulfons and sulfoxides", "Cleavage of methoxy ethers to alcohols",
            "Cleavage of alkoxy ethers to alcohols"
        ],
        "Azide Synthesis": [
            "Formation of Azides from halogens", "Formation of Azides from boronic acids"
        ],
        "Friedel-Crafts Reaction": [
            "Friedel-Crafts acylation", "Friedel-Crafts alkylation", "Friedel-Crafts alkylation with halide",
            "Friedel-Crafts acylation of alkynes"
        ],
        "Acylation Reactions": [
            "Friedel-Crafts acylation", "Acylation of secondary amines", "Acylation of olefines by aldehydes",
            "Acylation of primary amines",
            "Acylation of Nitrogen Nucleophiles by Acyl/Thioacyl/Carbamoyl Halides and Analogs_OS",
            "Acylation of Nitrogen Nucleophiles by Carboxylic Acids", "Acyl chloride with ammonia to amide"
        ],
        "Oxidation Reactions": [
            "Oxidation of aldehydes to carboxylic acids", "Oxidation of ketone to carboxylic acid",
            "Oxidation of boronic acids", "Oxidation of boronic esters", "Oxidation of nitrile to carboxylic acid",
            "Oxidation or Dehydrogenation of Alcohols to Aldehydes and Ketones",
            "Oxidation of amide to carboxylic acid",
            "Oxidation of alkene to carboxylic acid", "Oxidation of alcohol and aldehyde to ester",
            "Oxidation of alcohol to carboxylic acid"
        ],
        "[3+2]-Cycloadditions": [
            "[3+2]-cycloaddition of diazoalkane and alkene", "[3+2]-cycloaddition of diazoalkane and alkyne",
            "[3+2]-cycloaddition of diazoalkane and alpha-alkene", "[3+2]-cycloaddition of hydrazone and alkene",
            "[3+2]-cycloaddition of hydrazone and alkyne", "[3+2]-cycloaddition of diazoalkane and alpha-alkyne"
        ],
        "Aromatic Halogenation": [
            "Aromatic fluorination", "Aromatic chlorination", "Aromatic bromination", "Aromatic iodination"
        ],
        "Alcohol to alkyl halide conversion": [
            "Alkyl chlorides from alcohols", "Alkyl bromides from alcohols", "Alkyl iodides from alcohols"
        ],
        "Alcohol to acyl halide conversion": [
            "Acyl chlorides from alcohols", "Acyl bromides from alcohols", "Acyl iodides from alcohols"
        ],
        "Wohl-Ziegler Bromination": [
            "Wohl-Ziegler bromination benzyl primary", "Wohl-Ziegler bromination benzyl secondary",
            "Wohl-Ziegler bromination benzyl tertiary", "Wohl-Ziegler bromination allyl primary",
            "Wohl-Ziegler bromination allyl secondary", "Wohl-Ziegler bromination allyl tertiary",
            "Wohl-Ziegler bromination carbonyl primary", "Wohl-Ziegler bromination carbonyl secondary",
            "Wohl-Ziegler bromination carbonyl tertiary"
        ],
        "Amine to halide conversion": [
            "Primary amine to fluoride", "Primary amine to chloride",
            "Primary amine to bromide", "Primary amine to iodide"
        ],
        "Alcohol to chloride conversion": [
            "Alcohol to chloride_sulfonyl chloride", "Alcohol to chloride_SOCl2",
            "Alcohol to chloride_CHCl3", "Alcohol to chloride_CH2Cl2",
            "Alcohol to chloride_PCl5_ortho", "Alcohol to chloride_POCl3_ortho",
            "Alcohol to chloride_POCl3_para", "Alcohol to chloride_POCl3",
            "Alcohol to chloride_HCl", "Alcohol to chloride_Salt", "Alcohol to chloride_Other"
        ],
        "Sulfanyl to sulfinyl conversion": [
            "Sulfanyl to sulfinyl_peroxide", "Sulfanyl to sulfinyl_H2O2",
            "Sulfanyl to sulfinyl_H2O", "Sulfanyl to sulfinyl_SO3-",
            "Sulfanyl to sulfinyl_sulfonyl", "Sulfanyl to sulfinyl_MeOH",
            "Sulfanyl to sulfinyl_COO", "Sulfanyl to sulfinyl"
        ],
        "Halogenation": [
            "Chlorination", "Fluorination", "Iodination", "Bromination",
            "Hydrofluorination of methallyl alkenes", "Appel reaction",
        ],
        "Chan-Lam Reaction": [
            "Chan-Lam etherification", "Chan-Lam alcohol", "Chan-Lam amine"
        ],
        "Reductive Amination": [
            "Reductive amination with aldehyde", "Reductive amination with ketone", "Reductive amination with alcohol",
            "reductive amination"
        ],
        "Nitration": [
            "Aromatic nitration with HNO3", "Aromatic nitration with NO3 salt", "Aromatic nitration with NO2 salt",
            "Aromatic nitration with alkyl NO2", "Non-aromatic nitration with HNO3"
        ],
        "Urea synthesis": [
            "Urea synthesis via isocyanate and primary amine", "Urea synthesis via isocyanate and secondary amine",
            "Urea synthesis via isocyanate and diazo", "Urea synthesis via isocyanate and sulfonamide", "urea"
        ],
        "Amide to amine reduction": [
            "Reduction of primary amides to amines", "Reduction of secondary amides to amines",
            "Reduction of tertiary amides to amines"
        ],
        "Ester saponification": [
            "Ester saponification (methyl deprotection)", "Ester saponification (alkyl deprotection)",
        ],
        "Schotten-Baumann Reaction": [
            "Acyl chloride with primary amine to amide (Schotten-Baumann)", "Sulfonamide synthesis (Schotten-Baumann) primary amine",
            "Sulfonamide synthesis (Schotten-Baumann) secondary amine", "Schotten-Baumann_amide", "Schotten-Baumann to ester"
        ],
        "Esterification": [
            "Esterification of Carboxylic Acids", "Oxidative esterification of primary alcohols",
            "Esterification of hydrazones", "Mitsunobu esterification"
        ],
        "Transesterification": [
            "Transesterification", "Intramolecular transesterification/Lactone formation"
        ],
        "Benzothiazole synthesis": [
            "Benzothiazole formation from aldehyde", "Benzothiazole formation from acyl halide",
            "Benzothiazole formation from ester/carboxylic acid", "benzothiazole"
        ],
        "Benzoxazole synthesis": [
            "Benzoxazole formation from aldehyde", "Benzoxazole formation from acyl halide",
            "Benzoxazole formation from ester/carboxylic acid", "Benzoxazole formation (intramolecular)",
            "benzoxazole_arom-aldehyde", "benzoxazole_carboxylic-acid"
        ],
        "Benzimidazole synthesis": [
            "Benzimidazole formation from aldehyde", "Benzimidazole formation from acyl halide",
            "Benzimidazole formation from ester/carboxylic acid", "benzimidazole_derivatives_carboxylic-acid/ester",
            "benzimidazole_derivatives_aldehyde"
        ],
        "Oxirane functionalization": [
            "Oxirane functionalization with ketones", "Oxirane functionalization with alkyl iodide",
            "Oxirane functionalization with silyl chloride"
        ],
        "Thioether dynthesis": [
            "S-alkylation of thiols ", "S-alkylation of thiols (ethyl)",
            "S-alkylation of thiols with alcohols", "S-alkylation of thiols with alcohols (ethyl)", "thioether_nucl_sub"
        ]
    }
    subclass_dict = {subclass: key for key, subclasses in categorized_reactions.items() for subclass in subclasses}

    return subclass_dict
