#!/bin/bash
#PBS -N random_drfp_faiss
#PBS -l nodes=1:ppn=1:gpus=1
#PBS -l mem=40000mb
#PBS -l walltime=6:00:00

module load Faiss/1.7.4-foss-2023a-CUDA-12.1.1
module load PyTorch/2.1.2-foss-2023a-CUDA-12.1.1
module load Transformers/4.39.3-gfbf-2023a
module load SciPy-bundle/2023.07-gfbf-2023a
module load RDKit/2024.03.3-foss-2023a

export OMPI_MCA_mpi_warn_on_fork=0
source /kyukon/data/gent/432/vsc43212/venv/genrxn/bin/activate

# Hyperparameter Optimization
python /user/gent/432/vsc43212/genrxn/evaluate_retriever.py \
    --output /kyukon/scratch/gent/vo/000/gvo00008/vsc43212/genrxn/random_results/ --n-jobs 1 --k 1 5 10 20 50 100 --coverage-n 2000 --splits "random" --verbose --min-template-count 10

